version: 2.1

orbs:
    heroku: circleci/heroku@1.0.1

jobs:
    build:
        docker:
            - image: circleci/python:3.6.9 
        steps:
            - checkout
            - run:
                  name: Show directoryes
                  command: ls
    test:
        docker:
            - image: circleci/python:3.6.9 
        steps:
            - checkout
            - run:
                  name: running tests
                  command: pytest

workflows:
    Build and Test:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - hold:
                  type: approval
                  requires:
                      - test
            - heroku/deploy-via-git:
                  requires:
                      - hold
                  filters:
                      branches:
                          only: master


