version: 2.1

orbs:
    heroku: circleci/heroku@1.0.1

jobs:
    build:
        docker:
            - image: circleci/python:3.6.9 
        steps:
            - checkout
            - run:
                  name: Show directoryes
                  command: ls

workflows:
    Build and Test:
        jobs:
            - build
            - heroku/deploy-via-git:
                  filters:
                      branches:
                          only: master


